version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.5.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080"  
      - "7077:7077" 
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:3.5.3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077 
    depends_on:
      - spark-master  
    networks:
      - spark-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-spark
    environment:
      - JUPYTER_ENABLE_LAB=yes  
    ports:
      - "8888:8888"  
    depends_on:
      - spark-master  
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge 

